### ISSUE TITLE
Error loading Bruker EDS data (BCF files)

### ISSUE THREAD

**Issue by muddywellyboots** [hyperspy/hyperspy#1801]
I've acquired a Bruker EDS map in BCF format from a ROI in an SEM image. Originally the file contained both EBSD data, however I've just saved the EDS component to keep the file size down.

When I try and load the file
```python
import hyperspy.api as hs
bk = hs.load('eds.bcf')
```

I get the following error message
```python
~/Documents/hyperspy/hyperspy/io_plugins/bcf.py in _parse_image(self, xml_node, overview)
    671             if any(array1):
    672                 item = self.gen_hspy_item_dict_basic()
--> 673                 data = array1.reshape((image.height, image.width))
    674                 detector_name = str(img.find('./Description').text)
    675                 item['data'] = data

ValueError: cannot reshape array of size 114688 into shape (448,512)
```
The full error can be found at https://gist.github.com/muddywellyboots/b4a47283e873641ab6dd5219bea6231d

The file can be found at [eds.bcf.zip](https://github.com/hyperspy/hyperspy/files/1639757/eds.bcf.zip)

**Comment by magnunor** [comment]
I'm guessing @sem-geologist is the best person for this, since he has a lot of experience with the BCF format

**Comment by sem-geologist** [comment]
@muddywellyboots , I am trying to understand why this is broken. If you obtain normal hyperman (without ebsd) is it not opening in hyperspy as well? Can Esprit read this file? The problem I see here is that image which is saved in bcf have only half size; I guess it could be that image is in 8bit mode (differently when all up till now my observed images, all of them in 16bit). Could you describe your microscope a bit more in detail (the vendor, is bruker/Esprit setup on separate PC, previously bruker's setup always used its separate scanning and video card and converting analog image signal with 16bit resolution, while many major microscope vendors does only 8bit). It is my guess, I will look into this if I am right.

**Comment by sem-geologist** [comment]
Oh I see, there is tag <ItemSize> in the image header, which in your case is 1, and in all previous cases were 2. So I guess 2 means uint16, and 1 means uint8. It will be short fix. @muddywellyboots , thanks for reporting the bug. @francisco-dlp , could I attach the bug fix to #1779 ? or should I do separate PR?

**Comment by sem-geologist** [comment]
or maybe better not, this should go in separate PR,

@muddywellyboots , could you provide sample bcf (small as possible bcf), e.g. set image size to 100 and gather 16x16 map. so that we could include such file in our automatic code tests.

**Comment by sem-geologist** [comment]
I can't find in the xml part no ROI information on Overview images. So it is mega weird: file have 512x448 pixel image and hypermaps, and 3 Overview images but differently than previously studied version2 bcfs this one have no rectangle information pointing where this small region were produced. I "Love" bruker's consistency...

**Comment by muddywellyboots** [comment]
Thanks for looking into this, @sem-geologist. 
In answer to your questions, the microscope is a FEI Helios Plasma FIB and Esprit is running on a separate PC.

I've taken a number of small sample datasets to test.
-bcf3.bcf is a 5x4 ROI taken from a 100x100 image for both EBSD and EDS.
-bcf3-justeds.bcf is the above, but with just the EDS part saved
-bcf5.bcf is a 17x17 ROI from a 100x100 image for a standard EDS hypermap.
[bcf3.zip](https://github.com/hyperspy/hyperspy/files/1650276/bcf3.zip)
[bcf3-justeds.zip](https://github.com/hyperspy/hyperspy/files/1650277/bcf3-justeds.zip)
[bcf5.zip](https://github.com/hyperspy/hyperspy/files/1650278/bcf5.zip)

**Comment by sem-geologist** [comment]
Theoretically there should be no problem reading bcf3.bcf (ebsd data-bearing) file, however it have some strange date corruption (creation date, modification date, access date) in sfs container, I need to look into that.
@muddywellyboots , your ebsd containing bcf file, is it without ebsd interpretative step? the file inner tree looks quite different from what I was getting with Esprit 1.9.x. I mean is kikuchi bands only registered, but no analysis of it were run (Quantification?)?

**Comment by muddywellyboots** [comment]
Yes, bcf3.bcf (the file containing both EDS/EBSD) has not had any quantification run on it.
Let me know if I can do any more to help. Would be no problem for me to run the quantification on it and upload.

**Comment by sem-geologist** [comment]
Looks that there is chance to make ebsd containing file to be read to (only hypermap part for now, but this should bring some imporvement for future ebsd-hyperspy work).
I had identified the problem: it is that I have long time ago discarded some code which checked and read accordingly long list of internal sfs container files (where sfs is used for bcf (simple and ebsd ones) and particle analysis files `*.pan`. Particularly pan files can contain thousands of internal xml files. The sfs is subdivided into chunks, and simple bcf internal file tree normally fits into single chunk. Previous observations were showing that bruker uses 0x1000 for v1 bcf and 0x10000 for v2. Interestingly `bcf3-justeds.bcf` file follows that pattern, but ebsd containing bcf (`bcf3.bcf`) is highly optimized, and chunks are none of these, but 0xE49 size. File tree of that contains 32 items! instead of 3 or 4 items, and of course the tree does not fit into single chunk. And this is the problem, the code piece were removed in very early stage of bcf.py development as no files with more than 3 or 4 items were known, and no files were available with more items to use in tests.
I should refresh my memory, but I think v1 (older sfs) technology were not aligning the tree items to the beginning of the chunk, and this shared `bcf3.bcf` example does. As code is writen to be universal for v1 and v2 bcf, I should get some v1 ebsd bearing hypermaps (luckily We have EBSD on our dual beam machine and can do that) and see how they compare.

**Comment by sem-geologist** [comment]
Ok, I checked pan and v1 ebsd files: the file_items are aligned to the chunk, so at least that is consistent between versions.

**Comment by sem-geologist** [comment]
The initial fix I bring in #1833 allows to read `bcf3.bcf`, this however does not fix problem with reading `bcf3-justeds.bcf`, where file is severely uglified. @muddywellyboots , I guess reading primary `bcf3.bcf` without explicit extraction of eds (into `bcf3-justeds.bcf`) is better for you? @francisco-dlp , I probably should take care that `bcf3-justeds.bcf` – the again highly cropped-off metadata data sample  – could be as well open in hyperspy?

**Comment by sem-geologist** [comment]
@muddywellyboots , I don't know how I was getting previously huge problems with bcf3-justeds.bcf, but I found that it is much easier to fix than I thought. The latest PR is capable of opening all 3 bcf types you had shared.

**Comment by ericpre** [comment]
Fixed in #1833.

**Comment by sem-geologist** [comment]
I got contacted by @muddywellyboots , and I see I forgot one very important line. While #1833 makes three small files published above to open without a problem, I forgot, to add implementation of reading tag with uint size (e.g. 1 = uint8; 2 = uint16...), so in some huge v2 files dtype is wrong, and the error persist. This will be very small fix (few lines).  @ericpre , I am not sure it should be opened back? Maybe it is enough to push small PR without reopening this.
